# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:		  ./Rennan            
tagline:          Dotfiles
url:              http://rennanzera.github.io
paginate:         2
baseurl:          /
author:
  name:           Rennan Leite
  url:            https://twitter.com/rennanzera
  email:          rennanalfa@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
